### ISSUE TITLE
readVCFforCanopy

### ISSUE THREAD

**Issue by mayasheth** [yuchaojiang/MARATHON#2]
Hello! I am trying to run Canopy on a VCF containing daya from several tumor samples. However, when I use the command readVCFforCanopy(), I get the following error:

Error in readVCFforCanopy(myVCF) : 
  Please ensure the input file is in VCF format with first 9 column names: CHROM, POS, ID, REF, ALT, QUAL, FILTER, INFO, FORMAT, followed by one column per sample

I have checked the VCF and confirmed that this it is in the correct format- what else could be wrong?

**Comment by bwubb** [comment]
I believe it doesn't actually want a vcf file. You have to strip it of all header lines and # in front of CHROM

**Comment by mayasheth** [comment]
Thank you!! 

Follow up question- how does one choose the "K" and "numchain" values? 

I am running canopy.sample.nocna(), but keep getting the error "Error in if (r >= randr) { : missing value where TRUE/FALSE needed." I've traced this back to the addsamptree function but don't know how to fix it.

**Comment by mayasheth** [comment]
Additionally, my WM, Wm, epsilonM/m, C, and Y values all returned NULL- do you know why this may have happened?

**Comment by yuchaojiang** [comment]
Thanks Brad! Yes, I believe the current version needs a vcf without additional header information and the first row without the pound sign.

Gene, it was very coincident but I was literally using this code for one other project this morning and was about to email you. Can you update the function readVCFforCanopy in MARATHON to:


1)     Enables reading in vcf file with header information and with #CHROM as the first element. I am attaching a sample vcf.

vcf = scan("sample_w_header.vcf", what="character")
N = length(vcf)
id = which(vcf[1:1000]=="#CHROM")
vcf=vcf[id:N]

vcf=matrix(vcf, nrow=length(vcf)/(grep('^chr',vcf[1:100])[1]-1), byrow=T)
colnames(vcf)=vcf[1,]
vcf=vcf[-1,]
N0=nrow(vcf)


2)     Output genotype and reads matrix as well, in addition to vcfTargets, R, and X. The users usually need to screen for the somatic SNVs by looking at the genotype of normal and tumor. Can you add a note in the pipeline specifying this screening process?

Thanks,
Yuchao

**Comment by yuchaojiang** [comment]
K is the number of clones you want to test on. Numchain is the number of MCMC chains you want to randomly initiate for each different K values.
If you don’t understand what these mean, keep K=2:5 and numchain =10 (you can increase the latter depending on your computation power and the size of your run).

**Comment by yuchaojiang** [comment]
We need more details before we can help you..

**Comment by mayasheth** [comment]
Thanks for helping out! I ran readVCFforCanopy on a multi-sample vcf with WES data from 12 samples. Some positions have more than one alternate allele. When I ran this, I got a lot of warning messages about NAs induced by coercion, and wasn't sure why that happened. I replaced all NAs with 0 in the R and X matrices and passed them to canopy.sample.nocna()...  will this produce a valid output? What other information would be helpful to share?

**Comment by mayasheth** [comment]
Hello. I am just updated the Marathon package and am trying to run readVCFforCanopy on the same file I originally did successfully, using the file path as input. However, I get the following error: 

Error in matrix(RVector, nrow(AD), ncol(AD)) : 
  'data' must be of a vector type, was 'NULL'

What can I do about this?

**Comment by urrutiag** [comment]
Hi,

MARATHON::readVCFforCanopy is now set up to read true VCF files with header
and #CHROM.  This is the preferred format going forward.

The legacy function MARATHON::readVCFDataFrameforCanopy is still available
for "VCF type" files with no header and no # before CHROM like the one I
assume you used originally.

Thanks,
Gene

**Comment by mayasheth** [comment]
Hi Gene,


I am inputting a true VCF with header and #CHROM and still getting this error.


Thanks,
Maya

________________________________

**Comment by urrutiag** [comment]
OK could you please send the file?  Thanks

**Comment by mayasheth** [comment]
Hi,


The file is in a Google Drive folder here<https://drive.google.com/drive/folders/1yn9RnM69iQFx40Sl928-k2CYr9oRHr7C?usp=sharing>. I was now able to read the VCF, but running clustering step below gives me the following error:  "Running EM with 2 clusters... 1   Error in do_one(nmeth) : NA/NaN/Inf in foreign function call (arg 1)"


[cid:ec43768b-744f-4732-af7e-8176a93357f0]

Would appreciate any advice.

Thanks,
Maya

________________________________

**Comment by urrutiag** [comment]
Hi Maya,

I am glad that you were able to read the vcf file.  Thanks for sending the
vcf data.  I have added some checks to canopy.cluster to remove variants
with zero or NA for depth for any sample.  However the file contains 400K
variants, and I would suggest paring this number down.  I was able to run
canopy.cluster using the first 1000 variants from your data set.

I would suggest looking at our MARATHON sections for guidance:

How to generate SNA input for Canopy
and
Which CNAs and SNAs to use?

Thanks,
Gene

**Comment by mayasheth** [comment]
Hi Gene,


Thank you so much for this advice! I took a look at the sections you mentioned. Unfortunately, I don't have access to the raw sequencing data, so I am not sure how to appropriately pare down the variants. If I were to simply randomly select a subset of variants to use, what would an ideal number be?


Additionally, I re-installed all of the packages, but when I try to run canopy.cluster using the first 1000 variants, I get the following error:

Error in canopy.cluster(R = R, X = X, num_cluster = num_cluster, num_run = num_run) :
  object 'zeroRef' not found

What could be causing this?

Thanks,
Maya

________________________________

**Comment by urrutiag** [comment]
Hi Maya,

I just pushed the update to canopy.cluster.

If the list below is not practical for you, then I would suggest finding
the 500 to 1000 most highly variable variants in terms of  variance across
samples of variant allele frequency.   But make sure the variants have high
depth of coverage as stated below.

- Pass variant recalibration (VQSR) from GATK;
- Have only one alternative allele (one locus being double hit by two
different SNAs in one patient is very unlikely);
- Are highly deleterious (i.e., focuse on driver mutations) from functional
annotations (*ANNOVAR <http://annovar.openbioinformatics.org/en/latest/>*);
- Have low population variant frequency from the 1000 Genomes Project (if
no normal samples are available);
- Don’t reside in segmental duplication regions;
- Have high depth of coverage (total as well as mutated read depth);
- Reside in target baits (e.g., exonic regions for exome sequencing);

Thanks,
Gene

**Comment by mayasheth** [comment]
Hi Gene,


I've been trying to run Canopy on a selected set of ~700 variants with high total read depth and variability with a variety of subclone numbers. I haven't been able to cluster them, because I get this error:


Error in kmeans(mat, kmeans_k, iter.max = 100) :
  more cluster centers than distinct data points.


The post processing step after running the non-clustered algorithm has been giving me this error over all ranges of subclones:


No configuration has posterior probablity greater than the threshold!
Run sampling longer or reduce the threshold.
Error in config.summary[i, 1] : subscript out of bounds

The algorithm appears to have converged with max.simrun = 100,000, min.sumrun = 10,000 (the likelihood plots are asymptotic). The mean likelihood values and BIC are in the range of:

k = 8 : mean likelihood -1170432 ; BIC -2347637

Do you have any suggestions on what parameters to change, or should I select the variants I'm using differently? How would I reduce the threshold?

Thank you for your help,
Maya




________________________________

**Comment by mayasheth** [comment]
Gene,

So sorry for the multiple emails. I have been able to generate trees with a couple different subclone numbers. My research mentor and I are having a little trouble interpreting what the tree means; for example, how do the different nodes correspond to the samples?

We would greatly appreciate any help.

Thanks,

Maya

________________________________

**Comment by yuchaojiang** [comment]
I think you should read our PNAS paper carefully. It has all the details with regard to the input, output, and modeling.

Thanks,
Yuchao
________________________________
